live_config_reload = true
working_directory = "None"

[shell]
program = "/bin/bash"
args = ["-l", "-c", "zellij attach POGGIES 2> /dev/null || zellij -s POGGIES"]

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[colors.bright]
black = "#686868"
blue = "#5CCFE6"
cyan = "#95E6CB"
green = "#A6CC70"
magenta = "#FFEE99"
red = "#F27983"
white = "#FFFFFF"
yellow = "#FFCC66"

[colors.normal]
black = "#191E2A"
blue = "#73D0FF"
cyan = "#95E6CB"
green = "#BAE67E"
magenta = "#FFD580"
red = "#FF3333"
white = "#C7C7C7"
yellow = "#FFA759"

[colors.primary]
background = "#202734"
foreground = "#CBCCC6"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 12

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 2500
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 0.80
startup_mode = "Windowed"

[window.dimensions]
columns = 80
lines = 24

[window.padding]
x = 25
y = 20
